# Generated by Django 5.0 on 2024-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_municipality_code_ine_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalcode',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='postal_code',
            field=models.CharField(max_length=5),
        ),
    ]
