# Generated by Django 5.0 on 2024-04-13 18:47

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='end date')),
            ],
            options={
                'verbose_name': 'Administrator Community',
                'verbose_name_plural': 'Administrators Communities',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('IDcommunity', models.CharField(default=communities.models.generate_idcommunity_default, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('NIFcommunity', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='community nif')),
                ('nameCommunity', models.CharField(default='Mi comunidad', max_length=40, verbose_name='community name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(max_length=12, verbose_name='postal code')),
                ('main_contact_id', models.PositiveIntegerField(blank=True, null=True)),
                ('configurationCompleted', models.BooleanField(blank=True, null=True)),
                ('numberProperties', models.IntegerField(blank=True, null=True, verbose_name='number properties')),
                ('numberHouses', models.IntegerField(blank=True, null=True, verbose_name='number houses')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='PresidentCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='end date')),
            ],
            options={
                'verbose_name': 'President Community',
                'verbose_name_plural': 'Presidents Community',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('IDproperty', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='property ID')),
                ('numberProperty', models.CharField(max_length=50, verbose_name='property number')),
                ('typeProperty', models.CharField(choices=[('HOUSE', 'House'), ('PARKING', 'Parking'), ('OTHER', 'Other')], max_length=50, verbose_name='property type')),
                ('communityPropertyPercentage', models.FloatField(blank=True, null=True, verbose_name='community property percentage')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
