# Generated by Django 5.0.4 on 2024-05-21 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administratorcommunity',
            name='administratorCommunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administratorCommunity'),
        ),
        migrations.AddField(
            model_name='community',
            name='main_contact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='administratorcommunity',
            name='administratedCommunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='communities.community', verbose_name='administratedCommunity'),
        ),
        migrations.AddField(
            model_name='presidentcommunity',
            name='presidencyCommunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidents', to='communities.community', verbose_name='community'),
        ),
        migrations.AddField(
            model_name='presidentcommunity',
            name='presidentCommunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='presidentCommunity'),
        ),
        migrations.AddField(
            model_name='property',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='community'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
