# Generated by Django 5.0 on 2024-08-23 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='main_contact_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities_main', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='core.province'),
        ),
        migrations.AddField(
            model_name='personcommunity',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='communities.community'),
        ),
        migrations.AddField(
            model_name='property',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='communities.community'),
        ),
        migrations.AddField(
            model_name='propertyrelationship',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='communities.property'),
        ),
        migrations.AddField(
            model_name='usercommunityrole',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='communities.community'),
        ),
        migrations.AddField(
            model_name='usercommunityrole',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='communities.personcommunity'),
        ),
        migrations.AddField(
            model_name='usercommunityrole',
            name='roles',
            field=models.ManyToManyField(to='communities.role'),
        ),
        migrations.AddField(
            model_name='usercommunityrole',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyrelationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_relationships', to='communities.usercommunityrole'),
        ),
        migrations.AlterUniqueTogether(
            name='personcommunity',
            unique_together={('community', 'email'), ('community', 'person_id')},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('community', 'property_id')},
        ),
        migrations.AlterUniqueTogether(
            name='usercommunityrole',
            unique_together={('user', 'person', 'community')},
        ),
    ]
