# Generated by Django 5.0 on 2024-05-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommunityrole',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('tenant', 'Inquilino'), ('admin', 'Administrador'), ('temp', 'Temporal')], max_length=10),
        ),
    ]
