# Generated by Django 5.0 on 2024-08-29 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercommunityrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercommunityrole',
            name='neighbour_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usercommunityrole',
            unique_together={('community', 'neighbour_id'), ('person', 'community'), ('user', 'community')},
        ),
    ]
