# Generated by Django 5.0 on 2024-09-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personcommunity',
            unique_together={('community', 'person_id')},
        ),
        migrations.AlterField(
            model_name='personcommunity',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='communities.role'),
        ),
        migrations.AlterField(
            model_name='personcommunity',
            name='surnames',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='surnames'),
        ),
        migrations.AlterField(
            model_name='personcommunity',
            name='user_status',
            field=models.CharField(blank=True, choices=[('active', 'Activo'), ('disabled', 'Deshabilitado'), ('temp', 'Temporal'), ('not_registered', 'No registrado')], max_length=14, null=True),
        ),
    ]
