# Generated by Django 5.0 on 2024-08-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_usercommunityrole_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrelationship',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyrelationship',
            name='person',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyRelationship',
        ),
    ]
