# Generated by Django 5.0 on 2024-07-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_propertyrelationship_user_personcommunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrelationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_relationships', to='communities.personcommunity'),
        ),
    ]
