# Generated by Django 5.0 on 2024-07-19 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_personcommunity_person_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercommunityrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercommunityrole',
            name='user_status',
            field=models.CharField(choices=[('active', 'Activo'), ('disabled', 'Deshabilitado'), ('temp', 'Temporal')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='usercommunityrole',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('tenant', 'Inquilino'), ('admin', 'Administrador')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='usercommunityrole',
            unique_together={('user', 'community', 'role', 'user_status')},
        ),
        migrations.DeleteModel(
            name='CommunityRole',
        ),
    ]
