# Generated by Django 5.0 on 2024-07-24 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_usercommunityrole_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='main_contact_id',
        ),
        migrations.RemoveField(
            model_name='community',
            name='main_contact_type',
        ),
        migrations.AddField(
            model_name='community',
            name='mainUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities_main', to=settings.AUTH_USER_MODEL),
        ),
    ]
