# Generated by Django 5.0 on 2024-09-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='usage',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'Comercial'), ('STORAGE', 'Almacén-Estacionamiento'), ('RESIDENTIAL', 'Residencial'), ('INDUSTRIAL', 'Industrial')], max_length=50, null=True),
        ),
    ]
