# Generated by Django 5.0 on 2024-09-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_personcommunity_unique_together_and_more'),
        ('properties', '0002_alter_property_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrelationship',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='property_relationships', to='communities.personcommunity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='usage',
            field=models.CharField(blank=True, choices=[('COMERCIAL', 'Comercial'), ('ALMACEN-ESTACIONAMIENTO', 'Almacén-Estacionamiento'), ('RESIDENCIAL', 'Residencial'), ('INDUSTRIAL', 'Industrial')], max_length=50, null=True),
        ),
    ]
