# Generated by Django 5.0 on 2024-09-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_personcommunity_unique_together_and_more'),
        ('properties', '0003_propertyrelationship_person_alter_property_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrelationship',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_person_relationships', to='communities.community'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyrelationship',
            unique_together={('community', 'property', 'person', 'type')},
        ),
    ]
