# Generated by Django 5.0.4 on 2025-01-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimcomment',
            name='claim_comment_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
