# Generated by Django 5.0.4 on 2025-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_claim_id_claimcomment_claim_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
