# Generated by Django 5.0 on 2025-02-16 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('cif_nif', models.CharField(max_length=20, unique=True, verbose_name='CIF/NIF')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('type', models.CharField(max_length=50, verbose_name='Type of Service')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Rating (1-5)')),
                ('reviews', models.PositiveIntegerField(default=0, verbose_name='Number of Reviews')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('contact_person_email', models.EmailField(max_length=254, verbose_name='Contact Person Email')),
                ('contact_person_phone', models.CharField(max_length=20, verbose_name='Contact Person Phone')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['company_name'],
            },
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
