# Generated by Django 5.0 on 2024-09-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surnames',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='surnames'),
        ),
    ]
