# Generated by Django 5.0 on 2024-04-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documentID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='user ID'),
        ),
    ]
