# Generated by Django 5.0 on 2024-06-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactIsPublic',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='public contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='documentType',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('PASSPORT', 'Passport')], max_length=20, null=True, verbose_name='document type'),
        ),
    ]
