# Generated by Django 5.0 on 2024-07-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_usercommunityrole_unique_together_and_more'),
        ('members', '0002_user_contactispublic_user_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communities.community'),
        ),
    ]
