# Generated by Django 5.0 on 2024-04-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_documentid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrator',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='owner',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
