# Generated by Django 5.0 on 2024-06-24 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='type')),
                ('reservable', models.BooleanField(default=False, verbose_name='reservable')),
                ('reservation_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='reservation duration')),
                ('time_unit', models.CharField(blank=True, choices=[('MIN', 'Minutes'), ('HOUR', 'Hours'), ('DAY', 'Days')], max_length=4, null=True, verbose_name='time unit')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_areas', to='communities.community')),
            ],
            options={
                'verbose_name': 'Common Area',
                'verbose_name_plural': 'Common Areas',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('duration', models.PositiveIntegerField(verbose_name='duration')),
                ('time_unit', models.CharField(choices=[('MIN', 'Minutes'), ('HOUR', 'Hours'), ('DAY', 'Days')], max_length=4, verbose_name='time unit')),
                ('common_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='common_areas.commonarea')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['start_time'],
                'unique_together': {('common_area', 'start_time', 'end_time')},
            },
        ),
    ]
