# Generated by Django 5.0 on 2024-08-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_areas', '0001_initial'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonarea',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_areas', to='communities.community'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='common_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='common_areas.commonarea'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='communities.community'),
        ),
    ]
