# Generated by Django 5.0 on 2025-02-28 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_areas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commonarea',
            unique_together={('community', 'area_id')},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('common_area', 'start_time', 'end_time')},
        ),
    ]
