# Generated by Django 5.0.4 on 2025-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_areas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonarea',
            name='usage_end',
            field=models.TimeField(blank=True, null=True, verbose_name='usage end'),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='usage_start',
            field=models.TimeField(blank=True, null=True, verbose_name='usage start'),
        ),
    ]
