# Generated by Django 5.0.4 on 2025-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_areas', '0004_commonarea_usage_end_commonarea_usage_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('MIN', 'Minutes'), ('HOUR', 'Hours'), ('DAY', 'Days')], max_length=4, null=True, verbose_name='time unit'),
        ),
    ]
