# Generated by Django 5.0 on 2025-02-28 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('vote_type', models.CharField(choices=[('simple', 'Simple (Yes/No)'), ('multiple_choice', 'Multiple Choice')], max_length=20, verbose_name='vote type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='communities.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_votes', to=settings.AUTH_USER_MODEL)),
                ('eligible_voters', models.ManyToManyField(related_name='eligible_votes', to='communities.personcommunity')),
            ],
            options={
                'ordering': ['vote_id'],
                'unique_together': {('community', 'vote_id')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.PositiveIntegerField()),
                ('option_text', models.CharField(max_length=255, verbose_name='option_text')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='votes.vote')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_votes', to='communities.personcommunity')),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='communities.personcommunity')),
                ('options', models.ManyToManyField(blank=True, related_name='vote_records_multiple', to='votes.option')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_votes', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='votes.vote')),
            ],
            options={
                'unique_together': {('vote', 'neighbor')},
            },
        ),
    ]
