# Generated by Django 5.0 on 2024-05-06 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.folder'),
        ),
        migrations.AddField(
            model_name='document',
            name='log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
