# Generated by Django 5.0 on 2024-05-06 19:35

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_folder_document_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage='django.core.files.storage.FileSystemStorage', upload_to=documents.models.document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['application/pdf', 'text/plain', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'image/jpeg', 'image/jpg', 'image/png'])]),
        ),
    ]
