# Generated by Django 5.0 on 2024-05-06 19:47

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_name_document_title_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['application/pdf', 'text/plain', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'image/jpeg', 'image/jpg', 'image/png'])]),
        ),
    ]
