# Generated by Django 5.0 on 2024-07-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_personcommunity_person_id'),
        ('documents', '0004_alter_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['community', 'document_id']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['community', 'folder_id']},
        ),
        migrations.AddField(
            model_name='document',
            name='document_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('community', 'document_id')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('community', 'folder_id')},
        ),
    ]
