# Generated by Django 5.0 on 2024-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_options_alter_folder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folder_id',
            field=models.PositiveIntegerField(),
        ),
    ]
