# Generated by Django 5.0 on 2024-07-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_document_id_alter_folder_folder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='folder',
        ),
        migrations.AddField(
            model_name='document',
            name='folder_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
