# Generated by Django 5.0 on 2024-07-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_document_folder_document_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent_folder_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
