# Generated by Django 5.0 on 2024-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_rename_name_document_title_document_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
